### ISSUE TITLE
(v1.0) snippet

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/sylvia_patrick_Titanic_Survival_ML#29]
Thank you for providing a script to show proof that you can upload your date table. But please provide a snippet in your project repo's README.md file.

**Comment by tungpatrick** [comment]
I'm not quite sure I understand what you are asking for. Does this mean we should have a photo of our data table in the README of the project?

**Comment by aimirza** [comment]
Yes

**Comment by LeeYinYing** [comment]
Hi Ali,

I was wondering if the snippet is needed for the README in our current stage? Since the README is evolving away from a proposal format and more like a summary/report format. I don't see why the snippet would be needed in the current state, is there a reason why this snippet would be important to add into the README at the current stage?

**Comment by aimirza** [comment]
I was required to mention it back then :) It was required in the proposal. I wouldn't worry about it.
